### PR TITLE
Rubocop/integration-stage-2

### PR DESCRIPTION
**Pull request by JelF**
- Configured Rails/SkipsModelValidations (new cop)
- Fixed Metrics/BlockLength in 'rails' (fix, conflict)
- Disabled RSpec/ScatteredSetup (new cop)

### CODE REVIEW

**Comment by fiscal-cliff** [comment]
I'd consider increment_counter and decrement_counter as special case. Those methods do not require the warning since they obviously skip validations.

**Comment by JelF** [comment]
@fiscal-cliff have you ever seen it in our projects?

**Review by tycooon — APPROVED** [review]

**Comment by JelF** [comment]
I don't sure, that man who knows what he doing would use them along with other methods, which run on a single model. The only reason to use it could be used is to run more postress validations in more predictable way, and i think this should be marked as an exception any way.

However, `update_all` should be an exception because it run on collection

**Comment by fiscal-cliff** [comment]
ok

**Pull request merged**
